"""
Govee music modes exported from your devices.
Generated by govee-python-sdk.

⚠️  WARNING: DO NOT EDIT THIS FILE!
This file is automatically regenerated on each fetch and any manual changes will be lost.

Import music modes directly:
    from govee_music_modes import energic_h6008
"""
from govee.models import MusicMode


calm_h6061 = MusicMode(
    name="Calm",
    value=0,
    sku="H6061",
    metadata={'sensitivity': {'dataType': 'INTEGER', 'unit': 'unit.percent', 'range': {'min': 0, 'max': 100, 'precision': 1}, 'options': None, 'required': True}, 'autoColor': {'dataType': 'ENUM', 'unit': None, 'range': None, 'options': [{'name': 'on', 'value': 1}, {'name': 'off', 'value': 0}], 'required': False}, 'rgb': {'dataType': 'INTEGER', 'unit': None, 'range': {'min': 0, 'max': 16777215, 'precision': 1}, 'options': None, 'required': False}}
)

dynamic_h6061 = MusicMode(
    name="Dynamic",
    value=1,
    sku="H6061",
    metadata={'sensitivity': {'dataType': 'INTEGER', 'unit': 'unit.percent', 'range': {'min': 0, 'max': 100, 'precision': 1}, 'options': None, 'required': True}, 'autoColor': {'dataType': 'ENUM', 'unit': None, 'range': None, 'options': [{'name': 'on', 'value': 1}, {'name': 'off', 'value': 0}], 'required': False}, 'rgb': {'dataType': 'INTEGER', 'unit': None, 'range': {'min': 0, 'max': 16777215, 'precision': 1}, 'options': None, 'required': False}}
)

energic_h6061 = MusicMode(
    name="Energic",
    value=2,
    sku="H6061",
    metadata={'sensitivity': {'dataType': 'INTEGER', 'unit': 'unit.percent', 'range': {'min': 0, 'max': 100, 'precision': 1}, 'options': None, 'required': True}, 'autoColor': {'dataType': 'ENUM', 'unit': None, 'range': None, 'options': [{'name': 'on', 'value': 1}, {'name': 'off', 'value': 0}], 'required': False}, 'rgb': {'dataType': 'INTEGER', 'unit': None, 'range': {'min': 0, 'max': 16777215, 'precision': 1}, 'options': None, 'required': False}}
)

hopping_h6061 = MusicMode(
    name="Hopping",
    value=3,
    sku="H6061",
    metadata={'sensitivity': {'dataType': 'INTEGER', 'unit': 'unit.percent', 'range': {'min': 0, 'max': 100, 'precision': 1}, 'options': None, 'required': True}, 'autoColor': {'dataType': 'ENUM', 'unit': None, 'range': None, 'options': [{'name': 'on', 'value': 1}, {'name': 'off', 'value': 0}], 'required': False}, 'rgb': {'dataType': 'INTEGER', 'unit': None, 'range': {'min': 0, 'max': 16777215, 'precision': 1}, 'options': None, 'required': False}}
)

stacking_h6061 = MusicMode(
    name="Stacking",
    value=4,
    sku="H6061",
    metadata={'sensitivity': {'dataType': 'INTEGER', 'unit': 'unit.percent', 'range': {'min': 0, 'max': 100, 'precision': 1}, 'options': None, 'required': True}, 'autoColor': {'dataType': 'ENUM', 'unit': None, 'range': None, 'options': [{'name': 'on', 'value': 1}, {'name': 'off', 'value': 0}], 'required': False}, 'rgb': {'dataType': 'INTEGER', 'unit': None, 'range': {'min': 0, 'max': 16777215, 'precision': 1}, 'options': None, 'required': False}}
)

rippling_h6061 = MusicMode(
    name="Rippling",
    value=5,
    sku="H6061",
    metadata={'sensitivity': {'dataType': 'INTEGER', 'unit': 'unit.percent', 'range': {'min': 0, 'max': 100, 'precision': 1}, 'options': None, 'required': True}, 'autoColor': {'dataType': 'ENUM', 'unit': None, 'range': None, 'options': [{'name': 'on', 'value': 1}, {'name': 'off', 'value': 0}], 'required': False}, 'rgb': {'dataType': 'INTEGER', 'unit': None, 'range': {'min': 0, 'max': 16777215, 'precision': 1}, 'options': None, 'required': False}}
)

swiping_h6061 = MusicMode(
    name="Swiping",
    value=6,
    sku="H6061",
    metadata={'sensitivity': {'dataType': 'INTEGER', 'unit': 'unit.percent', 'range': {'min': 0, 'max': 100, 'precision': 1}, 'options': None, 'required': True}, 'autoColor': {'dataType': 'ENUM', 'unit': None, 'range': None, 'options': [{'name': 'on', 'value': 1}, {'name': 'off', 'value': 0}], 'required': False}, 'rgb': {'dataType': 'INTEGER', 'unit': None, 'range': {'min': 0, 'max': 16777215, 'precision': 1}, 'options': None, 'required': False}}
)

__all__ = [
    "calm_h6061",
    "dynamic_h6061",
    "energic_h6061",
    "hopping_h6061",
    "stacking_h6061",
    "rippling_h6061",
    "swiping_h6061",
]