"""
DIY scene aliases for easy access.
Generated by govee-python-sdk.

You can manually add your own aliases here - they will be preserved across syncs.

Example:
    from govee_diy_scene_aliases import my_custom_scene
    from govee_diy_scene_aliases import hogwarts_red  # Custom alias
"""
from .govee_diy_scenes import *


# H6061 DIY scenes
lighting_botgenerated_h6061 = H6061_13222011
beehive_flicker_h6061 = H6061_16519117
fairy_color_spin_h6061 = H6061_16793137
fairy_color_flow_h6061 = H6061_16793146
rainbow_test_h6061 = H6061_21407320
beeoutline_h6061 = H6061_21512828
pink_blend_h6061 = H6061_21512838

__all__ = [
    "beehive_flicker_h6061",
    "beeoutline_h6061",
    "fairy_color_flow_h6061",
    "fairy_color_spin_h6061",
    "lighting_botgenerated_h6061",
    "pink_blend_h6061",
    "rainbow_test_h6061",
]