"""
Device aliases for easy access.
Generated by govee-python-sdk.

You can manually add your own aliases here - they will be preserved across syncs.

Example:
    from govee_device_aliases import spotlight2_machine
    from govee_device_aliases import spotlight_hogwarts_express  # Custom alias
"""
from .govee_devices import *


# H6061 devices
glide_hexa = H6061_7122D005C1061F48

__all__ = [
    "glide_hexa",
]