"""
Govee devices exported from your account.
Generated by govee-python-sdk.

⚠️  WARNING: DO NOT EDIT THIS FILE!
This file is automatically regenerated on each fetch and any manual changes will be lost.
To add custom device aliases, edit govee_device_aliases.py instead.

Devices use SKU_ID naming for stability:
    from govee_devices import H7094_0E4BD65085060E50

Use aliases for friendly names:
    from govee_device_aliases import spotlight2_machine
"""
from govee.models import Device


H6061_7122D005C1061F48 = Device(
    id="71:22:D0:05:C1:06:1F:48",
    name="Glide Hexa",
    sku="H6061",
    ip=None,
    capabilities=['on_off', 'toggle', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'music_setting', 'dynamic_scene', 'dynamic_scene', 'toggle'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

__all__ = [
    "H6061_7122D005C1061F48",
]