"""
Govee built-in scenes exported from your account.
Generated by govee-python-sdk.

WARNING: DO NOT EDIT THIS FILE!
This file is automatically regenerated on each fetch and any manual changes will be lost.

Import scenes directly:
    from govee_scenes import sunset
"""
from govee.models import Scene


aurora_h6061 = Scene(
    name="Aurora",
    value={'id': 2248, 'paramId': 2356},
    sku="H6061",
    metadata={}
)

awaken_a_h6061 = Scene(
    name="Awaken A",
    value={'id': 15325, 'paramId': 24153},
    sku="H6061",
    metadata={}
)

awaken_b_h6061 = Scene(
    name="Awaken B",
    value={'id': 15326, 'paramId': 24154},
    sku="H6061",
    metadata={}
)

awaken_c_h6061 = Scene(
    name="Awaken C",
    value={'id': 15327, 'paramId': 24155},
    sku="H6061",
    metadata={}
)

birthday_h6061 = Scene(
    name="Birthday",
    value={'id': 4367, 'paramId': 4914},
    sku="H6061",
    metadata={}
)

breathe_h6061 = Scene(
    name="Breathe",
    value={'id': 2261, 'paramId': 2369},
    sku="H6061",
    metadata={}
)

christmas_h6061 = Scene(
    name="Christmas",
    value={'id': 4362, 'paramId': 4909},
    sku="H6061",
    metadata={}
)

colorful_h6061 = Scene(
    name="Colorful",
    value={'id': 4361, 'paramId': 4908},
    sku="H6061",
    metadata={}
)

crawl_h6061 = Scene(
    name="Crawl",
    value={'id': 4360, 'paramId': 4907},
    sku="H6061",
    metadata={}
)

dance_party_h6061 = Scene(
    name="Dance Party",
    value={'id': 2258, 'paramId': 2366},
    sku="H6061",
    metadata={}
)

disco_h6061 = Scene(
    name="Disco",
    value={'id': 2259, 'paramId': 2367},
    sku="H6061",
    metadata={}
)

dreamland_h6061 = Scene(
    name="Dreamland",
    value={'id': 2257, 'paramId': 2365},
    sku="H6061",
    metadata={}
)

dreamlike_h6061 = Scene(
    name="Dreamlike",
    value={'id': 2264, 'paramId': 2372},
    sku="H6061",
    metadata={}
)

easter_h6061 = Scene(
    name="Easter",
    value={'id': 4365, 'paramId': 4912},
    sku="H6061",
    metadata={}
)

energetic_h6061 = Scene(
    name="Energetic",
    value={'id': 2262, 'paramId': 2370},
    sku="H6061",
    metadata={}
)

fathers_day_h6061 = Scene(
    name="Father's Day",
    value={'id': 4364, 'paramId': 4911},
    sku="H6061",
    metadata={}
)

fire_h6061 = Scene(
    name="Fire",
    value={'id': 2250, 'paramId': 2358},
    sku="H6061",
    metadata={}
)

flow_h6061 = Scene(
    name="Flow",
    value={'id': 2273, 'paramId': 2381},
    sku="H6061",
    metadata={}
)

flower_field_h6061 = Scene(
    name="Flower Field",
    value={'id': 2251, 'paramId': 2359},
    sku="H6061",
    metadata={}
)

forest_h6061 = Scene(
    name="Forest",
    value={'id': 2245, 'paramId': 2353},
    sku="H6061",
    metadata={}
)

intersection_h6061 = Scene(
    name="Intersection",
    value={'id': 2271, 'paramId': 2379},
    sku="H6061",
    metadata={}
)

kaleidoscope_h6061 = Scene(
    name="Kaleidoscope",
    value={'id': 2272, 'paramId': 2380},
    sku="H6061",
    metadata={}
)

leisure_h6061 = Scene(
    name="Leisure",
    value={'id': 2717, 'paramId': 2825},
    sku="H6061",
    metadata={}
)

meditation_h6061 = Scene(
    name="Meditation",
    value={'id': 2265, 'paramId': 2373},
    sku="H6061",
    metadata={}
)

mothers_day_h6061 = Scene(
    name="Mother's Day",
    value={'id': 4363, 'paramId': 4910},
    sku="H6061",
    metadata={}
)

movie_h6061 = Scene(
    name="Movie",
    value={'id': 2253, 'paramId': 2361},
    sku="H6061",
    metadata={}
)

night_light_h6061 = Scene(
    name="Night Light",
    value={'id': 2718, 'paramId': 2826},
    sku="H6061",
    metadata={}
)

ocean_h6061 = Scene(
    name="Ocean",
    value={'id': 2244, 'paramId': 2352},
    sku="H6061",
    metadata={}
)

optimistic_h6061 = Scene(
    name="Optimistic",
    value={'id': 2266, 'paramId': 2374},
    sku="H6061",
    metadata={}
)

poker_h6061 = Scene(
    name="Poker",
    value={'id': 2269, 'paramId': 2377},
    sku="H6061",
    metadata={}
)

rainbow_h6061 = Scene(
    name="Rainbow",
    value={'id': 2247, 'paramId': 2355},
    sku="H6061",
    metadata={}
)

raining_h6061 = Scene(
    name="Raining",
    value={'id': 4359, 'paramId': 4906},
    sku="H6061",
    metadata={}
)

refreshing_h6061 = Scene(
    name="Refreshing",
    value={'id': 2267, 'paramId': 2375},
    sku="H6061",
    metadata={}
)

ripple_h6061 = Scene(
    name="Ripple",
    value={'id': 2252, 'paramId': 2360},
    sku="H6061",
    metadata={}
)

romantic_h6061 = Scene(
    name="Romantic",
    value={'id': 2256, 'paramId': 2364},
    sku="H6061",
    metadata={}
)

siren_h6061 = Scene(
    name="Siren",
    value={'id': 2260, 'paramId': 2368},
    sku="H6061",
    metadata={}
)

soothing_h6061 = Scene(
    name="Soothing",
    value={'id': 2263, 'paramId': 2371},
    sku="H6061",
    metadata={}
)

stacking_h6061 = Scene(
    name="Stacking",
    value={'id': 2270, 'paramId': 2378},
    sku="H6061",
    metadata={}
)

star_h6061 = Scene(
    name="Star",
    value={'id': 2249, 'paramId': 2357},
    sku="H6061",
    metadata={}
)

starry_sky_h6061 = Scene(
    name="Starry Sky",
    value={'id': 4358, 'paramId': 4905},
    sku="H6061",
    metadata={}
)

sunset_glow_h6061 = Scene(
    name="Sunset Glow",
    value={'id': 2246, 'paramId': 2354},
    sku="H6061",
    metadata={}
)

sweet_h6061 = Scene(
    name="Sweet",
    value={'id': 2268, 'paramId': 2376},
    sku="H6061",
    metadata={}
)

valentines_day_h6061 = Scene(
    name="Valentine's Day",
    value={'id': 4366, 'paramId': 4913},
    sku="H6061",
    metadata={}
)

white_light_h6061 = Scene(
    name="White Light",
    value={'id': 9159, 'paramId': 15246},
    sku="H6061",
    metadata={}
)

__all__ = [
    "aurora_h6061",
    "awaken_a_h6061",
    "awaken_b_h6061",
    "awaken_c_h6061",
    "birthday_h6061",
    "breathe_h6061",
    "christmas_h6061",
    "colorful_h6061",
    "crawl_h6061",
    "dance_party_h6061",
    "disco_h6061",
    "dreamland_h6061",
    "dreamlike_h6061",
    "easter_h6061",
    "energetic_h6061",
    "fathers_day_h6061",
    "fire_h6061",
    "flow_h6061",
    "flower_field_h6061",
    "forest_h6061",
    "intersection_h6061",
    "kaleidoscope_h6061",
    "leisure_h6061",
    "meditation_h6061",
    "mothers_day_h6061",
    "movie_h6061",
    "night_light_h6061",
    "ocean_h6061",
    "optimistic_h6061",
    "poker_h6061",
    "rainbow_h6061",
    "raining_h6061",
    "refreshing_h6061",
    "ripple_h6061",
    "romantic_h6061",
    "siren_h6061",
    "soothing_h6061",
    "stacking_h6061",
    "star_h6061",
    "starry_sky_h6061",
    "sunset_glow_h6061",
    "sweet_h6061",
    "valentines_day_h6061",
    "white_light_h6061",
]